name: Homework_1
on:
  push:
    branches:
      - homework-1
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./homework_1

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: sudo apt install valgrind clang-tidy libgtest-dev lcov

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: run tests
        run: ./build/parsetag/tests/test
        
