name: homework_2
on:
  push:
    branches:
      - homework-2
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./homework_2

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: sudo apt install valgrind clang-tidy libgtest-dev

      - name: run build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          make

      - name: run linter
        run: |
          clang-tidy -checks=* -header-filter=. -p ./build/ examples/main.c

      - name: run memcheck
        run: |
          valgrind ./build/homework_2
