name: homework_2
on:
  push:
    branches:
      - homework-2
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./homework_2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install valgrind clang-tidy libgtest-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          make

      - name: Build multiprocessed
        run: |
          mkdir build_mp
          cd build_mp
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DMOODLIB_MP=ON
          make

      - name: Lint
        run: |
          clang-tidy -checks=* -header-filter=. -p ./build/ examples/main.c

      - name: Lint multiprocessed
        run: |
          clang-tidy -checks=* -header-filter=. -p ./build_mp/ examples/main.c

      - name: Test
        run: |
          cd build && ctest

      - name: Test with memcheck
        run: |
          cd build
          valgrind --leak-check=full --show-leak-kinds=all ./lib/mood/tests/test_mood

      - name: Test multiprocessed
        run: |
          cd build_mp && ctest

      - name: Test multiprocessed with memcheck
        run: |
          cd build_mp
          valgrind --leak-check=full --show-leak-kinds=all ./lib/mood_mp/tests/test_mood

      - name: Memcheck
        run: |
          valgrind --leak-check=full --show-leak-kinds=all ./build/homework_2
        
      - name: Memcheck multiprocessed
        run: |
          valgrind --leak-check=full --show-leak-kinds=all ./build_mp/homework_2
