name: homework_2
on:
  push:
    branches:
      - homework-2
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./homework_2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install valgrind clang-tidy libgtest-dev lcov

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          make

      - name: Build multiprocessed version
        run: |
          mkdir build_mp
          cd build_mp
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DMOODLIB_MP=ON
          make

      - name: Lint
        run: |
          clang-tidy -checks=* -header-filter=.* -p ./build/ examples/basic_example_1/src/main.c
          clang-tidy -checks=* -header-filter=.* -p ./build_mp/ examples/basic_example_1/src/main.c
          
      - name: Test (Unit)
        run: |
          cd build
          ctest --output-on-failure

      - name: Test (Unit) with memcheck
        run: |
          cd build
          mkdir memory_report
          cp -r ../lib/reader_utils/tests/data/ .
          valgrind --leak-check=full --show-leak-kinds=all --log-file=./memory_report/mood.txt ./lib/mood/tests/test_mood
          valgrind --leak-check=full --show-leak-kinds=all --log-file=./memory_report/moodmp.txt ./lib/mood_mp/tests/test_mood_mp
          valgrind --leak-check=full --show-leak-kinds=all --log-file=./memory_report/reader_utils.txt ./lib/reader_utils/tests/test_reader_utils
        
      - name: Compose coverage report
        run: |
          cd build
          lcov --capture --directory . -o coverage.info
          lcov --remove coverage.info '/usr/include/*' -o filtered_coverage.info
          genhtml -o coverage_report filtered_coverage.info

      - name: Upload memory report
        uses: actions/upload-artifact@v2
        with:
          name: report-memory
          path: ./homework_2/build/memory_report/
          if-no-files-found: error

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./homework_2/build/coverage_report/
          if-no-files-found: error
