name: homework_2
on:
  push:
    branches:
      - homework-2
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./homework_2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install valgrind clang-tidy libgtest-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          make

      - name: Build multiprocessed version
        run: |
          mkdir build_mp
          cd build_mp
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DMOODLIB_MP=ON
          make

      - name: Lint
        run: |
          clang-tidy -checks=* -header-filter=.* -p ./build/ examples/main.c
          clang-tidy -checks=* -header-filter=.* -p ./build_mp/ examples/main.c
          
      - name: Test (Unit)
        run: |
          cd build
          ctest --verbose --output-on-failure

      - name: Test (Unit) with memcheck
        run: |
          cd build
          valgrind --leak-check=full --show-leak-kinds=all ./lib/mood/tests/test_mood
          valgrind --leak-check=full --show-leak-kinds=all ./lib/mood_mp/tests/test_mood_mp

          # Запуск теста из этой директории, так как тест использует файлы из нее.
          # p.s. не разобрался, как запустить ctest под valgrind-ом без сильных заморочек,
          # но знаю, что для ctest-теста можно определить директорию, в которой тест
          # должен быть запущен
          
          cd lib/reader_utils/tests/
          valgrind --leak-check=full --show-leak-kinds=all \
          ../../../build/lib/reader_utils/tests/test_reader_utils
