name: homework_2
on:
  push:
    branches:
      - homework-2
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./homework_2

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: sudo apt install valgrind clang-tidy libgtest-dev

      - name: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          make

      - name: build multiprocessed
        run: |
          mkdir build_mp
          cd build_mp
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DMOODLIB_MP=ON
          make

      - name: lint
        run: |
          clang-tidy -checks=* -header-filter=. -p ./build/ examples/main.c

      - name: lint multiprocessed
        run:
          clang-tidy -checks=* -header-filter=. -p ./build_mp/ examples/main.c

      - name: memcheck
        run: |
          valgrind ./build/homework_2
        
      - name: memcheck multiprocessed
        run: |
          valgrind ./build_mp/homework_2

